[project]
name = "esp32-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "esptool>=4.11.0",
    "mpremote>=1.27.0",
]
